# .github/workflows/monitor_version.yml

# 1. Nome do Workflow: Aparece na interface do Actions
name: Monitoramento de Versão do Validador

# 2. Gatilhos (Triggers): QUANDO o workflow deve ser executado
on:
  # Execução agendada (neste exemplo, a cada 5 minutos)
  schedule:
    # Formato CRON: minuto hora dia_do_mês mês dia_da_semana
    # '*/5 * * * *' = A cada 5 minutos
    - cron: '*/5 * * * *'
  # Permite que o usuário acione manualmente
  workflow_dispatch:
  # Opcional: Executar em push (se quiser testar após mudar o código)
  # push:
  #   branches: [ main ]

# 3. Jobs: A(s) tarefa(s) a ser(em) executada(s)
jobs:
  check_version:
    # runs-on: ONDE o job será executado (o runner)
    runs-on: ubuntu-latest
    
    # 4. Variáveis de Ambiente do Job (para passar o Secret)
    env:
      # O valor do Secret 'EXPECTED_RELEASE' é injetado no job como ENV
      EXPECTED_RELEASE: ${{ secrets.EXPECTED_RELEASE }}
      
    # 5. Steps: A lista de ações a executar sequencialmente
    steps:
      - name: Checkout do Código 
        # Usa uma action pré-definida para baixar o código do repositório
        uses: actions/checkout@v4
        
      - name: Configurar Node.js
        # Usa uma action para configurar o ambiente Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Instalar Dependências (Opcional, se houver)
        # Comando shell para instalar pacotes (não é o nosso caso, mas é comum)
        # run: npm install 
          
      - name: Executar Script de Verificação
        # Comando shell para rodar o nosso script Node.js
        run: node version_checker.js
        
      - name: Enviar Notificação de Alarme
        # Esta etapa só é executada se a etapa anterior (run) FALHAR
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3
        with:
          # Detalhes do e-mail... (configurados com Secrets)
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: '[ALERTA] MUDANÇA DE VERSÃO DO VALIDADOR!'
          to: seu_email@exemplo.com
          body: |
            A versão do validador mudou.
            Verifique o log do workflow para a nova versão.